M48
; DRILL file {KiCad 6.0.10+dfsg-1~bpo11+1} date Thu Mar  2 20:38:38 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-02T20:38:38+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
%
G90
G05
T1
X45.02Y46.29
X45.02Y40.51
T2
X35.525Y39.108
X36.541Y44.188
X37.557Y39.108
T3
X38.2Y31.35
X38.2Y19.3
X45.2Y31.35
X45.2Y19.3
T0
M30
